sudo: required

language: node_js
node_js:
  - '10'

services:
  - docker

before_script:
  - yarn

script:
  - yarn lint
  - yarn test --coverage
  - make build

notifications:
  slack:
    secure: JcpafPd/aOPT9KRo3i+36azZ2HZzCfyZIi/16/r5aUMBBUdJVyE3y694rV/DqLdMX6547HZhvblDSZb+M6IitL9Re1h8i86kNEJyoXxYaRQgAYsivGnHWyScLOlExBL7OKfnLHs0k4VMNUulqiriJnfoV+2V8qj/fSUwdpL9GBrwx+fZp8ayU5wIkYJwOZrHSS95SLOOdDv92waIBMZVEtVMyrGI4gp0Z9D9HBxW4ploNFXUecp69l4/oetpsbluH2M+wfxP+e+LRJ4BmVOb2a/SFSTxjQXp/xJHw/gRDtLFRg5BgFC6bSacOqlC/qumiwWLpToXWTtJIytL0b+x3S0aRXorPY4ZCqgc1DDx6EFArAViUH1cIu5Bb831BHENHyrQ3tvN8a0lIST6L+g52jbHoVSKyZy1j78cDeGAQlwR2Kx0f3w2MHF+UEn7cI+B6ofv29YYeGXQ5hSzOGN50Xj3i0FH1+L+3snZekqQIJIZLTQqri7G+5BU4yCCy3JoLks2R9D3gMrlGCo1rwEsI6wQELBnSc4iJKCXFOkP31mlQFQfoMRzEDx0aEZ3oCe1/N8JXpje29Ncq0OhMCjTLKAZlR74YatDWO5Pd31wuN8ZBkV2SCEFQYy4fhf7N3Hl7aPpRziWJAW6FfuWHgdCbtZZlAXVwEGLQWr/fAeECw0=
